### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by sahithyandev** [barelyhuman/tillwhen-issues#2]
When I attempt to visit TillWhen, the browser fails to load it with "Too many redirects".

**Comment by barelyhuman** [comment]
Thanks for reporting, I'll check this out, is there a specific URL that's doing this or just anything leads to this?

**Comment by sahithyandev** [comment]
All urls. It's been doing that at least for the past 3 days.

Nice work btw. 👍

**Comment by barelyhuman** [comment]
Oh damn, cool I’ll get onto it

**Comment by barelyhuman** [comment]
There seems to be a connection leak on the DB, I'll dig deeper into it but for now, if you can validate if it's up or still behaving like before?

**Comment by sahithyandev** [comment]
It's up now. 👍

**Comment by barelyhuman** [comment]
Great! 👍
